// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/_auth.ts
var notAuthenticated = {
  content: [{ type: "text", text: "N\xE3o autenticado. Conecte-se com sua conta de admin." }],
  isError: true
};
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "Listar posts do blog",
  description: "Lista os posts do blog com filtro opcional por status (draft/published) e busca por t\xEDtulo.",
  inputSchema: {
    status: z.enum(["draft", "published"]).optional().describe("Filtra por status do post."),
    search: z.string().trim().min(1).optional().describe("Busca por parte do t\xEDtulo."),
    limit: z.number().int().min(1).max(100).default(20).describe("N\xFAmero m\xE1ximo de posts.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    let query = supabaseForUser(ctx).from("blog_posts").select("id, title, slug, status, category, excerpt, published_at, updated_at, views_count").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Ver post do blog",
  description: "Retorna o conte\xFAdo completo de um post do blog pelo slug.",
  inputSchema: { slug: z2.string().trim().min(1).describe("Slug do post.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail(`Nenhum post encontrado com o slug "${slug}".`);
    return ok(data);
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
function slugify(value) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
var create_blog_post_default = defineTool3({
  name: "create_blog_post",
  title: "Criar post do blog",
  description: "Cria um novo post do blog. Por padr\xE3o salva como rascunho (draft).",
  inputSchema: {
    title: z3.string().trim().min(1).describe("T\xEDtulo do post."),
    content: z3.string().trim().min(1).describe("Conte\xFAdo do post em HTML."),
    excerpt: z3.string().trim().optional().describe("Resumo curto do post."),
    slug: z3.string().trim().optional().describe("Slug personalizado; gerado do t\xEDtulo se omitido."),
    category: z3.string().trim().optional().describe("Nome da categoria."),
    featured_image: z3.string().url().optional().describe("URL da imagem de capa."),
    status: z3.enum(["draft", "published"]).default("draft").describe("Status de publica\xE7\xE3o.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const status = input.status ?? "draft";
    const { data, error } = await supabaseForUser(ctx).from("blog_posts").insert({
      title: input.title,
      content: input.content,
      excerpt: input.excerpt ?? null,
      slug: input.slug?.trim() ? slugify(input.slug) : slugify(input.title),
      category: input.category ?? null,
      featured_image: input.featured_image ?? null,
      status,
      published_at: status === "published" ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).select().maybeSingle();
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/update-blog-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var update_blog_post_default = defineTool4({
  name: "update_blog_post",
  title: "Atualizar post do blog",
  description: "Atualiza campos de um post existente identificado pelo slug (t\xEDtulo, conte\xFAdo, resumo, categoria, imagem ou status).",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Slug do post a atualizar."),
    title: z4.string().trim().min(1).optional(),
    content: z4.string().trim().min(1).optional(),
    excerpt: z4.string().trim().optional(),
    category: z4.string().trim().optional(),
    featured_image: z4.string().url().optional(),
    status: z4.enum(["draft", "published"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ slug, status, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const patch = { ...fields, updated_at: (/* @__PURE__ */ new Date()).toISOString() };
    Object.keys(patch).forEach((key) => patch[key] === void 0 && delete patch[key]);
    if (status) {
      patch.status = status;
      if (status === "published") patch.published_at = (/* @__PURE__ */ new Date()).toISOString();
    }
    const { data, error } = await supabaseForUser(ctx).from("blog_posts").update(patch).eq("slug", slug).select().maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail(`Nenhum post encontrado com o slug "${slug}".`);
    return ok(data);
  }
});

// src/lib/mcp/tools/list-contact-requests.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contact_requests_default = defineTool5({
  name: "list_contact_requests",
  title: "Listar mensagens de contato",
  description: "Lista as mensagens recebidas pelo formul\xE1rio de contato, com filtro opcional por n\xE3o lidas.",
  inputSchema: {
    only_unread: z5.boolean().default(false).describe("Retornar somente mensagens n\xE3o lidas."),
    limit: z5.number().int().min(1).max(100).default(20).describe("N\xFAmero m\xE1ximo de mensagens.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_unread, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    let query = supabaseForUser(ctx).from("contact_requests").select("id, name, email, phone, subject, message, is_read, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_unread) query = query.eq("is_read", false);
    const { data, error } = await query;
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/tools/list-newsletter-subscribers.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z6 } from "npm:zod@^3.25.76";
var list_newsletter_subscribers_default = defineTool6({
  name: "list_newsletter_subscribers",
  title: "Listar inscritos da newsletter",
  description: "Lista os inscritos da newsletter com origem e data de inscri\xE7\xE3o.",
  inputSchema: {
    limit: z6.number().int().min(1).max(200).default(50).describe("N\xFAmero m\xE1ximo de inscritos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("newsletter_subscribers").select("id, name, email, source, consent, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    return error ? fail(error.message) : ok(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "ottofzjtxfutkjoksvsu";
var mcp_default = defineMcp({
  name: "marcus-t-melo-automacao-ia-humanizada",
  title: "Marcus T. Melo Automa\xE7\xE3o & IA Humanizada",
  version: "0.1.0",
  instructions: "Ferramentas administrativas do site Marcus T. Melo: gerenciar posts do blog, ler mensagens do formul\xE1rio de contato e consultar inscritos da newsletter. O usu\xE1rio conectado precisa ter papel de admin no site.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_blog_posts_default,
    get_blog_post_default,
    create_blog_post_default,
    update_blog_post_default,
    list_contact_requests_default,
    list_newsletter_subscribers_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
